name: Testing[master]
on:
  push:
    branches: [ master ]
jobs:
  # Build the Hello World test application
  build-magicshapes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: mikelduke/love.js@master
      id: love-js-build
      with:
        title: 'magicshapes'
        source_file: 'test/magicshapes.love'
    # Upload the resulting artifacts
    - uses: actions/upload-artifact@v1
      with:
        name: love-js
        path: ${{ steps.love-js-build.outputs.love-js-output }}
    - name: Publish generated content to GitHub Pages
      uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
      with:
        dir: ${{ steps.love-js-build.outputs.love-js-output }}
        branch: gh-pages
        token: ${{ secrets.ACCESS_TOKEN }}
